# Generated by Django 3.2.8 on 2022-01-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoomcar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trayecto',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='trayecto',
            name='origen',
        ),
        migrations.RemoveField(
            model_name='trayecto',
            name='paradas',
        ),
        migrations.RemoveField(
            model_name='trayecto',
            name='piloto',
        ),
        migrations.RemoveField(
            model_name='trayecto',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.DeleteModel(
            name='Trayecto',
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
