# Generated by Django 3.2.8 on 2022-02-04 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoomcar', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='twitterToken',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fechaReserva',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 18, 20, 13, 232654)),
        ),
    ]
